### ISSUE TITLE
Leaving edit page before upload completes throws an error?

### ISSUE THREAD

**Issue by wesoudshoorn** [daybreakers-co/frontend#14]
Sometimes get to see an error that a Photo ID wasn't found?

**Comment by matsimitsu** [comment]
There are two scenario's where this can happen.

1. Upload a hero photo and navigate back to the post page before the hero has uploaded. In this case the is a new "hero" element in our post cache as we just made it, but it doesn't contain a photo, because we aborted the transfer.

2. Upload a hero photo that completes and navigate back to the post. It looks like the same scenario, but here we have a valid photo, but the cache isn't updated with this new photo, so from the post component's perspective we added a hero section without a photo. 

One way of solving this issue is to not render elements that are not "valid" e.g. a hero section must contain a photo, the downside is that in the case of scenario 2, there _is_ a photo it's just not in the cache yet.

Another option is to invalidate the cache, I'm still looking into how this works with Apollo (invalidating/re-fetching a query from a different (editpost) component.

**Comment by matsimitsu** [comment]
For now I've added a `fetchPolicy` of `network-only` this means that every time the page is loaded, it does a http request for the post data, instead of reading it from the cache. 
http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy

I'll leave this issue open to see if there's a better way to do this (ideally we let Apollo cache everything as it provides a faster user experience)
